# See https://libgunshotmatch.readthedocs.io/en/latest/api/method.html for parameters
# TODO: proper docs for the config file (à la whey's for pyproject.toml)

[method.intensity_matrix]
crop_mass_range = [
    50,
    400,
]
savitzky_golay = true
tophat = true
tophat_structure_size = "1.5m"

[method.peak_detection]
points = 9
scans = 2

[method.peak_filter]
noise_filter = true
noise_threshold = 2
base_peak_filter = [
    73,
    147,
]
rt_range = [3.0, 38.0]

[method.alignment]
min_peaks = 5

[method.consolidate]
name_filter=["*silane*", "*silyl*", "*silox*"]
min_match_factor=600
min_appearances=5
